os: linux
language: shell

env:
  - ZEND_VERSION=2.0.20 JDK=14

install:
  - source ./scripts/install.sh
  - source ./scripts/setup-env.sh

script: ./scripts/build.sh

before_deploy:
  - git config --local user.name $GITHUB_USERNAME
  - git config --local user.email $GITHUB_EMAIL
  - if [[ -z $TRAVIS_TAG ]]; then export TRAVIS_TAG=$TRAVIS_BRANCH; fi

deploy:
  provider: releases
  token: $GITHUB_AUTH
  file_glob: true
  file: "./releases/*"
  skip_cleanup: true
  overwrite: true
  draft: true
  name: $READABLE_NAME
  on:
    all_branches: true

jobs:
  include:
    - stage: "Builds and Deploy"
      os: osx
      osx_image: xcode9.4
      language: shell
    -
      os: linux
      dist: bionic
      language: shell
    -
      os: windows
      language: shell
      before_install:
        - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine
        - powershell Install-WindowsFeature Net-Framework-Core
        - cinst -y wixtoolset
